//! Request limits the HTTP surface enforces, exported to TypeScript alongside
//! the DTOs so a client can respect them without hand-copying the number.
//!
//! These are not ts-rs types (a `const` is a value, not a shape), so
//! `bin/export-dto.rs` writes them into `limits.ts` itself and the index writer
//! skips that file.

/// Upper bound on one `POST /skills/apply-updates` body's `names`, and a HARD
/// one — the request is refused, not truncated.
///
/// The mutation seam reads the Lock once and scans the agents once, but neither
/// hoist bounds the real cost: every resolvable row still runs its own
/// install+lock transaction, which re-scans every agent under the mutation lock
/// because that read has to be fresh. One request therefore occupies a mutation
/// worker for `O(names)` transactions, and Rocket has only CPU-count workers.
///
/// A client with more outdated skills than this must send several batches.
pub const MAX_BATCH_NAMES: usize = 256;

#[cfg(test)]
mod tests {
	/// Generation is manual (`bun run generate:dto`) and nothing in CI diffs the
	/// tree afterwards, so lowering the Rust cap without regenerating would leave
	/// the desktop chunking above what the server accepts — and every other check
	/// would still pass. This is the drift alarm.
	#[test]
	fn the_generated_desktop_limit_matches_this_one() {
		let generated = std::fs::read_to_string(concat!(
			env!("CARGO_MANIFEST_DIR"),
			"/../desktop/src/generated/dto/limits.ts"
		))
		.expect("limits.ts is generated by bin/export-dto.rs and committed");
		let expected = format!(
			"export const MAX_BATCH_NAMES = {};",
			super::MAX_BATCH_NAMES
		);
		assert!(
			generated.contains(&expected),
			"stale generated limit — re-run `bun run generate:dto`.\n\
			 expected: {expected}\ngot:\n{generated}"
		);
	}
}
